import type { ProviderManifest } from './domain'

export const providerManifests: ProviderManifest[] = [
  {
    id: 'minimax',
    label: 'MiniMax',
    description: 'A clean baseline adaptor for text-to-image and image editing flows.',
    version: '2026.05',
    accent: '#8ab4ff',
    auth: {
      type: 'apiKey',
      header: 'Authorization',
      envKey: 'MINIMAX_API_KEY',
    },
    operations: ['generate', 'edit'],
    capabilities: {
      supportsGenerate: true,
      supportsEdit: true,
      supportsMultiImage: true,
      supportsNegativePrompt: false,
      supportsCustomSize: true,
      supportsAspectRatio: true,
      supportsSeed: true,
      supportsBase64Output: true,
    },
    defaultModelId: 'image-01',
    providerOptions: [
      {
        id: 'promptOptimizer',
        label: 'Prompt optimizer',
        description: 'Let MiniMax refine prompts before generation.',
        control: 'boolean',
        defaultValue: false,
      },
      {
        id: 'aigcWatermark',
        label: 'AIGC watermark',
        description: 'Add an AIGC watermark to generated images.',
        control: 'boolean',
        defaultValue: false,
      },
      {
        id: 'styleType',
        label: 'Style type',
        description: 'Style preset for image-01-live. One of: 漫画, 元气, 中世纪, 水彩.',
        control: 'select',
        defaultValue: '元气',
        options: [
          { value: '漫画', label: '漫画' },
          { value: '元气', label: '元气' },
          { value: '中世纪', label: '中世纪' },
          { value: '水彩', label: '水彩' },
        ],
        appliesToModels: ['image-01-live'],
      },
      {
        id: 'styleWeight',
        label: 'Style weight',
        description: 'Style weight for image-01-live in (0, 1]. Higher means stronger style effect.',
        control: 'number',
        defaultValue: 0.8,
        min: 0.01,
        max: 1,
        step: 0.01,
        appliesToModels: ['image-01-live'],
      },
    ],
    models: [
      {
        id: 'image-01',
        label: 'image-01',
        operations: ['generate', 'edit'],
        constraints: {
          maxImages: 9,
          promptMaxLength: 1500,
          supportedAspectRatios: ['1:1', '16:9', '4:3', '3:2', '2:3', '3:4', '9:16', '21:9'],
          sizePresets: [
            { width: 1024, height: 1024 },
            { width: 1280, height: 720 },
            { width: 1152, height: 864 },
            { width: 1248, height: 832 },
            { width: 832, height: 1248 },
            { width: 864, height: 1152 },
            { width: 720, height: 1280 },
            { width: 1344, height: 576 },
          ],
        },
        featureFlags: {
          promptOptimizer: true,
          watermark: true,
        },
      },
      {
        id: 'image-01-live',
        label: 'image-01-live',
        operations: ['generate', 'edit'],
        constraints: {
          maxImages: 9,
          promptMaxLength: 1500,
          supportedAspectRatios: ['1:1', '16:9', '4:3', '3:2', '2:3', '3:4', '9:16'],
          sizePresets: [
            { width: 1024, height: 1024 },
            { width: 1280, height: 720 },
            { width: 1152, height: 864 },
            { width: 1248, height: 832 },
            { width: 832, height: 1248 },
            { width: 864, height: 1152 },
            { width: 720, height: 1280 },
          ],
          supportsCustomSize: false,
        },
        featureFlags: {
          promptOptimizer: true,
        },
      },
    ],
  },
  {
    id: 'stepfun',
    label: 'StepFun',
    description: 'The standard StepFun image adaptor with documented /v1 image endpoints.',
    version: '2026.05',
    accent: '#7f8cff',
    auth: {
      type: 'apiKey',
      header: 'Authorization',
      envKey: 'STEPFUN_API_KEY',
    },
    operations: ['generate', 'edit'],
    capabilities: {
      supportsGenerate: true,
      supportsEdit: true,
      supportsMultiImage: false,
      supportsNegativePrompt: true,
      supportsCustomSize: true,
      supportsAspectRatio: false,
      supportsSeed: true,
      supportsBase64Output: true,
    },
    defaultModelId: 'step-image-edit-2',
    providerOptions: [
      {
        id: 'textMode',
        label: 'Text mode',
        description: 'Optimize the run for text-heavy images and typography scenes.',
        control: 'boolean',
        defaultValue: false,
        appliesToModels: ['step-image-edit-2'],
      },
      {
        id: 'styleReferenceSource',
        label: 'Style reference source',
        description: 'Public URL or data URL used as the StepFun style reference source.',
        control: 'text',
        defaultValue: '',
        appliesToModels: ['step-1x-medium'],
      },
      {
        id: 'styleReferenceWeight',
        label: 'Style reference weight',
        description: 'Weight for style reference on step-1x-medium style-conditioned runs.',
        control: 'number',
        defaultValue: 1,
        min: 0,
        max: 2,
        step: 0.05,
        appliesToModels: ['step-1x-medium'],
      },
      {
        id: 'sourceWeight',
        label: 'Source weight',
        description: 'Controls how strongly image2image should stay close to the source.',
        control: 'number',
        defaultValue: 0.5,
        min: 0.05,
        max: 1,
        step: 0.05,
        appliesToModels: ['step-1x-medium'],
      },
      {
        id: 'steps',
        label: 'Steps',
        description: 'Number of denoising steps. Higher values improve quality but increase latency.',
        control: 'number',
        defaultValue: 8,
        min: 1,
        max: 50,
        step: 1,
        appliesToModels: ['step-image-edit-2'],
      },
      {
        id: 'cfgScale',
        label: 'CFG scale',
        description: 'Classifier-free guidance scale. Higher values follow the prompt more strictly.',
        control: 'number',
        defaultValue: 1.0,
        min: 1.0,
        max: 10.0,
        step: 0.1,
        appliesToModels: ['step-image-edit-2'],
      },
      {
        id: 'steps',
        label: 'Steps',
        description: 'Number of denoising steps. Higher values improve quality but increase latency.',
        control: 'number',
        defaultValue: 50,
        min: 1,
        max: 100,
        step: 1,
        appliesToModels: ['step-1x-medium'],
      },
      {
        id: 'cfgScale',
        label: 'CFG scale',
        description: 'Classifier-free guidance scale. Higher values follow the prompt more strictly.',
        control: 'number',
        defaultValue: 7.5,
        min: 1.0,
        max: 10.0,
        step: 0.1,
        appliesToModels: ['step-1x-medium'],
      },
      {
        id: 'steps',
        label: 'Steps',
        description: 'Number of denoising steps. Higher values improve quality but increase latency.',
        control: 'number',
        defaultValue: 28,
        min: 1,
        max: 100,
        step: 1,
        appliesToModels: ['step-1x-edit'],
      },
      {
        id: 'cfgScale',
        label: 'CFG scale',
        description: 'Classifier-free guidance scale. Higher values follow the prompt more strictly.',
        control: 'number',
        defaultValue: 6,
        min: 1.0,
        max: 10.0,
        step: 0.1,
        appliesToModels: ['step-1x-edit'],
      },
      {
        id: 'responseFormat',
        label: 'Response format',
        description: 'Choose whether results come back as URL references or base64 payloads.',
        control: 'select',
        defaultValue: 'url',
        options: [
          { value: 'url', label: 'Temporary URL' },
          { value: 'b64_json', label: 'Base64 payload' },
        ],
      },
    ],
    models: [
      {
        id: 'step-image-edit-2',
        label: 'step-image-edit-2',
        operations: ['generate', 'edit'],
        constraints: {
          maxImages: 1,
          promptMaxLength: 512,
          sizePresets: [
            { width: 1024, height: 1024 },
            { width: 1360, height: 768 },
            { width: 896, height: 1184 },
            { width: 1184, height: 896 },
            { width: 768, height: 1360 },
          ],
        },
        featureFlags: {
          negativePrompt: true,
          textMode: true,
        },
      },
      {
        id: 'step-1x-medium',
        label: 'step-1x-medium',
        operations: ['generate', 'edit'],
        constraints: {
          maxImages: 1,
          promptMaxLength: 1024,
          sizePresets: [
            { width: 256, height: 256 },
            { width: 512, height: 512 },
            { width: 768, height: 768 },
            { width: 1024, height: 1024 },
            { width: 1280, height: 800 },
            { width: 800, height: 1280 },
          ],
        },
        featureFlags: {
          styleReference: true,
        },
      },
      {
        id: 'step-1x-edit',
        label: 'step-1x-edit',
        operations: ['edit'],
        constraints: {
          maxImages: 1,
          promptMaxLength: 512,
          sizePresets: [
            { width: 512, height: 512 },
            { width: 768, height: 768 },
            { width: 1024, height: 1024 },
          ],
        },
      },
    ],
  },
  {
    id: 'stepfun-plan',
    label: 'StepFun Plan',
    description: 'An experimental StepFun Plan adaptor for testing observed image endpoints under the step_plan namespace.',
    version: '2026.05',
    accent: '#b58cff',
    auth: {
      type: 'apiKey',
      header: 'Authorization',
      envKey: 'STEPFUN_API_KEY',
    },
    operations: ['generate', 'edit'],
    capabilities: {
      supportsGenerate: true,
      supportsEdit: true,
      supportsMultiImage: false,
      supportsNegativePrompt: true,
      supportsCustomSize: true,
      supportsAspectRatio: false,
      supportsSeed: true,
      supportsBase64Output: true,
    },
    defaultModelId: 'step-image-edit-2',
    providerOptions: [
      {
        id: 'textMode',
        label: 'Text mode',
        description: 'Optimize the run for text-heavy images and typography scenes.',
        control: 'boolean',
        defaultValue: false,
        appliesToModels: ['step-image-edit-2'],
      },
      {
        id: 'steps',
        label: 'Steps',
        description: 'Number of denoising steps. Higher values improve quality but increase latency.',
        control: 'number',
        defaultValue: 8,
        min: 1,
        max: 50,
        step: 1,
        appliesToModels: ['step-image-edit-2'],
      },
      {
        id: 'cfgScale',
        label: 'CFG scale',
        description: 'Classifier-free guidance scale. Higher values follow the prompt more strictly.',
        control: 'number',
        defaultValue: 1.0,
        min: 1.0,
        max: 10.0,
        step: 0.1,
        appliesToModels: ['step-image-edit-2'],
      },
      {
        id: 'responseFormat',
        label: 'Response format',
        description: 'Choose whether results come back as URL references or base64 payloads.',
        control: 'select',
        defaultValue: 'url',
        options: [
          { value: 'url', label: 'Temporary URL' },
          { value: 'b64_json', label: 'Base64 payload' },
        ],
      },
    ],
    models: [
      {
        id: 'step-image-edit-2',
        label: 'step-image-edit-2',
        operations: ['generate', 'edit'],
        constraints: {
          maxImages: 1,
          promptMaxLength: 512,
          sizePresets: [
            { width: 1024, height: 1024 },
            { width: 1360, height: 768 },
            { width: 896, height: 1184 },
            { width: 1184, height: 896 },
            { width: 768, height: 1360 },
          ],
        },
        featureFlags: {
          negativePrompt: true,
          textMode: true,
        },
      },
    ],
  },
  {
    id: 'sensenova',
    label: 'SenseNova',
    description: 'SenseNova U1 Fast adaptor optimized for infographic generation with 2K resolution support.',
    version: '2026.05',
    accent: '#ff8c69',
    auth: {
      type: 'apiKey',
      header: 'Authorization',
      envKey: 'SENSENOVA_API_KEY',
    },
    operations: ['generate'],
    capabilities: {
      supportsGenerate: true,
      supportsEdit: false,
      supportsMultiImage: false,
      supportsNegativePrompt: false,
      supportsCustomSize: false,
      supportsAspectRatio: true,
      supportsSeed: false,
      supportsBase64Output: false,
    },
    defaultModelId: 'sensenova-u1-fast',
    providerOptions: [],
    models: [
      {
        id: 'sensenova-u1-fast',
        label: 'sensenova-u1-fast',
        operations: ['generate'],
        constraints: {
          maxImages: 1,
          promptMaxLength: 4096,
          supportedAspectRatios: [
            '2:3',
            '3:2',
            '3:4',
            '4:3',
            '4:5',
            '5:4',
            '1:1',
            '16:9',
            '9:16',
            '21:9',
            '9:21',
          ],
          sizePresets: [
            { width: 1664, height: 2496 },
            { width: 2496, height: 1664 },
            { width: 1760, height: 2368 },
            { width: 2368, height: 1760 },
            { width: 1824, height: 2272 },
            { width: 2272, height: 1824 },
            { width: 2048, height: 2048 },
            { width: 2752, height: 1536 },
            { width: 1536, height: 2752 },
            { width: 3072, height: 1376 },
            { width: 1344, height: 3136 },
          ],
        },
      },
    ],
  },
]
