import type { ProviderManifest } from './domain'

export const providerManifests: ProviderManifest[] = [
  {
    id: 'minimax',
    label: 'MiniMax',
    description: 'A clean baseline adaptor for text-to-image and image editing flows.',
    version: '2026.05',
    accent: '#8ab4ff',
    auth: {
      type: 'apiKey',
      header: 'Authorization',
      envKey: 'MINIMAX_API_KEY',
    },
    operations: ['generate', 'edit'],
    capabilities: {
      supportsGenerate: true,
      supportsEdit: true,
      supportsMultiImage: true,
      supportsNegativePrompt: false,
      supportsCustomSize: true,
      supportsAspectRatio: true,
      supportsSeed: true,
      supportsBase64Output: true,
    },
    defaultModelId: 'image-01',
    providerOptions: [
      {
        id: 'promptOptimizer',
        label: 'Prompt optimizer',
        description: 'Let MiniMax refine prompts before generation.',
        control: 'boolean',
        defaultValue: false,
      },
    ],
    models: [
      {
        id: 'image-01',
        label: 'image-01',
        operations: ['generate', 'edit'],
        constraints: {
          maxImages: 9,
          promptMaxLength: 1500,
          supportedAspectRatios: ['1:1', '16:9', '4:3', '3:2', '2:3', '3:4', '9:16', '21:9'],
          sizePresets: [
            { width: 1024, height: 1024 },
            { width: 1280, height: 720 },
            { width: 1536, height: 1024 },
          ],
        },
        featureFlags: {
          promptOptimizer: true,
          watermark: true,
        },
      },
      {
        id: 'image-01-live',
        label: 'image-01-live',
        operations: ['edit'],
        constraints: {
          maxImages: 9,
          promptMaxLength: 1500,
          supportedAspectRatios: ['1:1', '16:9', '4:3', '3:2', '2:3', '3:4', '9:16'],
        },
        featureFlags: {
          promptOptimizer: true,
        },
      },
    ],
  },
  {
    id: 'stepfun',
    label: 'StepFun',
    description: 'The standard StepFun image adaptor with documented /v1 image endpoints.',
    version: '2026.05',
    accent: '#7f8cff',
    auth: {
      type: 'apiKey',
      header: 'Authorization',
      envKey: 'STEPFUN_API_KEY',
    },
    operations: ['generate', 'edit'],
    capabilities: {
      supportsGenerate: true,
      supportsEdit: true,
      supportsMultiImage: false,
      supportsNegativePrompt: true,
      supportsCustomSize: true,
      supportsAspectRatio: false,
      supportsSeed: true,
      supportsBase64Output: true,
    },
    defaultModelId: 'step-image-edit-2',
    providerOptions: [
      {
        id: 'textMode',
        label: 'Text mode',
        description: 'Optimize the run for text-heavy images and typography scenes.',
        control: 'boolean',
        defaultValue: false,
        appliesToModels: ['step-image-edit-2'],
      },
      {
        id: 'styleReferenceSource',
        label: 'Style reference source',
        description: 'Public URL or data URL used as the StepFun style reference source.',
        control: 'text',
        defaultValue: '',
        appliesToModels: ['step-1x-medium'],
      },
      {
        id: 'styleReferenceWeight',
        label: 'Style reference weight',
        description: 'Weight for style reference on step-1x-medium style-conditioned runs.',
        control: 'number',
        defaultValue: 1,
        min: 0,
        max: 2,
        step: 0.05,
        appliesToModels: ['step-1x-medium'],
      },
      {
        id: 'sourceWeight',
        label: 'Source weight',
        description: 'Controls how strongly image2image should stay close to the source.',
        control: 'number',
        defaultValue: 0.5,
        min: 0.05,
        max: 1,
        step: 0.05,
        appliesToModels: ['step-1x-medium'],
      },
      {
        id: 'responseFormat',
        label: 'Response format',
        description: 'Choose whether results come back as URL references or base64 payloads.',
        control: 'select',
        defaultValue: 'url',
        options: [
          { value: 'url', label: 'Temporary URL' },
          { value: 'b64_json', label: 'Base64 payload' },
        ],
      },
    ],
    models: [
      {
        id: 'step-image-edit-2',
        label: 'step-image-edit-2',
        operations: ['generate', 'edit'],
        constraints: {
          maxImages: 1,
          promptMaxLength: 512,
          sizePresets: [
            { width: 1024, height: 1024 },
            { width: 1360, height: 768 },
            { width: 896, height: 1184 },
            { width: 1184, height: 896 },
            { width: 768, height: 1360 },
          ],
        },
        featureFlags: {
          negativePrompt: true,
          textMode: true,
        },
      },
      {
        id: 'step-1x-medium',
        label: 'step-1x-medium',
        operations: ['generate', 'edit'],
        constraints: {
          maxImages: 1,
          promptMaxLength: 1024,
          sizePresets: [
            { width: 256, height: 256 },
            { width: 512, height: 512 },
            { width: 768, height: 768 },
            { width: 1024, height: 1024 },
            { width: 1280, height: 800 },
            { width: 800, height: 1280 },
          ],
        },
        featureFlags: {
          styleReference: true,
        },
      },
      {
        id: 'step-1x-edit',
        label: 'step-1x-edit',
        operations: ['edit'],
        constraints: {
          maxImages: 1,
          promptMaxLength: 512,
          sizePresets: [
            { width: 512, height: 512 },
            { width: 768, height: 768 },
            { width: 1024, height: 1024 },
          ],
        },
      },
    ],
  },
  {
    id: 'stepfun-plan',
    label: 'StepFun Plan',
    description: 'An experimental StepFun Plan adaptor for testing observed image endpoints under the step_plan namespace.',
    version: '2026.05',
    accent: '#b58cff',
    auth: {
      type: 'apiKey',
      header: 'Authorization',
      envKey: 'STEPFUN_API_KEY',
    },
    operations: ['generate', 'edit'],
    capabilities: {
      supportsGenerate: true,
      supportsEdit: true,
      supportsMultiImage: false,
      supportsNegativePrompt: true,
      supportsCustomSize: true,
      supportsAspectRatio: false,
      supportsSeed: true,
      supportsBase64Output: true,
    },
    defaultModelId: 'step-image-edit-2',
    providerOptions: [
      {
        id: 'textMode',
        label: 'Text mode',
        description: 'Optimize the run for text-heavy images and typography scenes.',
        control: 'boolean',
        defaultValue: false,
        appliesToModels: ['step-image-edit-2'],
      },
      {
        id: 'responseFormat',
        label: 'Response format',
        description: 'Choose whether results come back as URL references or base64 payloads.',
        control: 'select',
        defaultValue: 'url',
        options: [
          { value: 'url', label: 'Temporary URL' },
          { value: 'b64_json', label: 'Base64 payload' },
        ],
      },
    ],
    models: [
      {
        id: 'step-image-edit-2',
        label: 'step-image-edit-2',
        operations: ['generate', 'edit'],
        constraints: {
          maxImages: 1,
          promptMaxLength: 512,
          sizePresets: [
            { width: 1024, height: 1024 },
            { width: 1360, height: 768 },
            { width: 896, height: 1184 },
            { width: 1184, height: 896 },
            { width: 768, height: 1360 },
          ],
        },
        featureFlags: {
          negativePrompt: true,
          textMode: true,
        },
      },
    ],
  },
]
